// <auto-generated />
using GameBackendAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameBackendAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260911133114_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameBackendAPI.Enteties.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Coins")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GameBackendAPI.Enteties.UserWeapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("WeaponId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WeaponId");

                    b.ToTable("UserWeapons");
                });

            modelBuilder.Entity("GameBackendAPI.Enteties.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Weapons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Damage = 10,
                            Name = "Pistol",
                            Price = 500
                        },
                        new
                        {
                            Id = 2,
                            Damage = 22,
                            Name = "AK 47",
                            Price = 5000
                        },
                        new
                        {
                            Id = 3,
                            Damage = 45,
                            Name = "ShotGun",
                            Price = 4000
                        },
                        new
                        {
                            Id = 4,
                            Damage = 22,
                            Name = "M468",
                            Price = 5000
                        },
                        new
                        {
                            Id = 5,
                            Damage = 14,
                            Name = "UMP-45",
                            Price = 3000
                        },
                        new
                        {
                            Id = 6,
                            Damage = 20,
                            Name = "Buldog",
                            Price = 4500
                        },
                        new
                        {
                            Id = 7,
                            Damage = 25,
                            Name = "Revolver",
                            Price = 1500
                        },
                        new
                        {
                            Id = 8,
                            Damage = 40,
                            Name = "ShotCannon",
                            Price = 2500
                        },
                        new
                        {
                            Id = 9,
                            Damage = 12,
                            Name = "SMG",
                            Price = 1000
                        },
                        new
                        {
                            Id = 10,
                            Damage = 13,
                            Name = "MP9",
                            Price = 2500
                        },
                        new
                        {
                            Id = 11,
                            Damage = 18,
                            Name = "Revolver-Small",
                            Price = 1000
                        },
                        new
                        {
                            Id = 12,
                            Damage = 14,
                            Name = "AKS-74U",
                            Price = 3000
                        },
                        new
                        {
                            Id = 13,
                            Damage = 12,
                            Name = "MP7",
                            Price = 2750
                        },
                        new
                        {
                            Id = 14,
                            Damage = 50,
                            Name = "ShotGun-2",
                            Price = 4000
                        });
                });

            modelBuilder.Entity("GameBackendAPI.Enteties.UserWeapon", b =>
                {
                    b.HasOne("GameBackendAPI.Enteties.User", "User")
                        .WithMany("Inventory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameBackendAPI.Enteties.Weapon", "Weapon")
                        .WithMany()
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("GameBackendAPI.Enteties.User", b =>
                {
                    b.Navigation("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
